/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;

import DAO.LoaiSanPhamDAO;
import DAO.SanPhamDAO;
import entity.LoaiSanPham;
import entity.SanPham;
import exception.FormatVietNamException;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import tienich.Auth;
import tienich.ImageHelper;
import tienich.LocalVietNam;
import tienich.MsgBox;

/**
 *
 * @author SuongNguyen
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    CardLayout cardlayout;

    public static String tongtienTT;

    public Home() {
        initComponents();
        cardlayout = (CardLayout) pnlScreenMain.getLayout();
        setLocationRelativeTo(null);

        initialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        pnlMenu = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnLoaiSanPham = new javax.swing.JButton();
        btnLuong = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        pnlScreenMain = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        pnlOrder = new javax.swing.JPanel();
        pnlSanPham = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        cbxLoaiSanPham2 = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SanPhamBoard = new javax.swing.JPanel();
        pnlThanhToan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatHang = new javax.swing.JTable();
        btnThanhToan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1250, 705));

        desktop.setPreferredSize(new java.awt.Dimension(1250, 705));

        pnlMenu.setBackground(new java.awt.Color(59, 175, 218));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));

        btnOrder.setBackground(new java.awt.Color(59, 175, 218));
        btnOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/order.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrder.setFocusPainted(false);
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrder.setPreferredSize(new java.awt.Dimension(87, 33));
        btnOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(59, 175, 218));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(59, 175, 218));
        btnSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/product.png"))); // NOI18N
        btnSanPham.setText("Sản phẩm");
        btnSanPham.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSanPham.setFocusPainted(false);
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(59, 175, 218));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/employee.png"))); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanVien.setFocusPainted(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnLoaiSanPham.setBackground(new java.awt.Color(59, 175, 218));
        btnLoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLoaiSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/type.png"))); // NOI18N
        btnLoaiSanPham.setText("Loại sản phẩm");
        btnLoaiSanPham.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnLoaiSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoaiSanPham.setFocusPainted(false);
        btnLoaiSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoaiSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSanPhamActionPerformed(evt);
            }
        });

        btnLuong.setBackground(new java.awt.Color(59, 175, 218));
        btnLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLuong.setForeground(new java.awt.Color(255, 255, 255));
        btnLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/salary.png"))); // NOI18N
        btnLuong.setText("Lương");
        btnLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuong.setFocusPainted(false);
        btnLuong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLuong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongActionPerformed(evt);
            }
        });

        btnHoaDon.setBackground(new java.awt.Color(59, 175, 218));
        btnHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/receipt.png"))); // NOI18N
        btnHoaDon.setText("Hoá đơn");
        btnHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoaDon.setFocusPainted(false);
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setBackground(new java.awt.Color(59, 175, 218));
        btnDoiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/changepass.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnDoiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(59, 175, 218));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/total.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDoiMatKhau)
                .addGap(0, 0, 0)
                .addComponent(btnThongKe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDoiMatKhau, btnLoaiSanPham, btnThongKe});

        pnlScreenMain.setLayout(new java.awt.CardLayout());

        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDangXuat.setBackground(new java.awt.Color(255, 51, 51));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnlHome.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 700, 114, 40));

        lblMenu.setIcon(new javax.swing.ImageIcon("hinhanh/menu.png"));
        pnlHome.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pnlScreenMain.add(pnlHome, "card2");

        jPanel12.setBackground(new java.awt.Color(59, 175, 218));

        cbxLoaiSanPham2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxLoaiSanPham2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxLoaiSanPham2.setPreferredSize(new java.awt.Dimension(82, 30));
        cbxLoaiSanPham2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaiSanPham2ItemStateChanged(evt);
            }
        });

        txtTimKiem.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbxLoaiSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxLoaiSanPham2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        SanPhamBoard.setBackground(new java.awt.Color(255, 255, 255));
        SanPhamBoard.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        jScrollPane2.setViewportView(SanPhamBoard);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pnlThanhToan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(255, 255, 255)));

        jLabel2.setBackground(new java.awt.Color(59, 175, 218));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đặt hàng");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 28));

        tblDatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Tên", "Số lượng", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDatHang.setRequestFocusEnabled(false);
        tblDatHang.setRowHeight(35);
        tblDatHang.getTableHeader().setReorderingAllowed(false);
        tblDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatHang);
        if (tblDatHang.getColumnModel().getColumnCount() > 0) {
            tblDatHang.getColumnModel().getColumn(0).setMinWidth(0);
            tblDatHang.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblDatHang.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDatHang.getColumnModel().getColumn(1).setMaxWidth(200);
            tblDatHang.getColumnModel().getColumn(2).setMaxWidth(80);
            tblDatHang.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        btnThanhToan.setBackground(new java.awt.Color(102, 255, 51));
        btnThanhToan.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel6.setText("Tổng tiền");

        lblTongTien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongTien.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(101, 101, 101)
                .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien)
                    .addComponent(jLabel6))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnLamMoi.setBackground(new java.awt.Color(255, 0, 51));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThanhToanLayout = new javax.swing.GroupLayout(pnlThanhToan);
        pnlThanhToan.setLayout(pnlThanhToanLayout);
        pnlThanhToanLayout.setHorizontalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLamMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );
        pnlThanhToanLayout.setVerticalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanhToanLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlThanhToanLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addComponent(pnlSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlScreenMain.add(pnlOrder, "card3");

        desktop.setLayer(pnlMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(pnlScreenMain, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlScreenMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlScreenMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        cardlayout.show(pnlScreenMain, "card3");
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        cardlayout.show(pnlScreenMain, "card2");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        if (!isAccess()) {
            return;
        }
        showForm(new QuanLySanPham());
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        if (!isAccess()) {
            return;
        }
        showForm(new QuanLyNhanVien());
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSanPhamActionPerformed
        if (!isAccess()) {
            return;
        }
        showForm(new QuanLyLoaiSanPham());
    }//GEN-LAST:event_btnLoaiSanPhamActionPerformed

    private void btnLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongActionPerformed
        showForm(new QuanLyLuong());
    }//GEN-LAST:event_btnLuongActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        if (!isAccess()) {
            return;
        }
        showForm(new QuanLyHoaDon());
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        showForm(new DoiMatKhau());
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        if (!isAccess()) {
            return;
        }
        showForm(new ThongKe());
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        tongtienTT = lblTongTien.getText();
        if (tableThanhToan.getRowCount() == 0) {
            MsgBox.notify("Vui lòng chọn sản phẩm trước.", this);
            return;
        }
        showForm(new ThanhToan(tableThanhToan));

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cbxLoaiSanPham2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaiSanPham2ItemStateChanged
        LoaiSanPham a = ((LoaiSanPham) comboboxLoai.getSelectedItem());
        List<SanPham> snList = sanPhamDAO.selectByTen(txtTimKiem.getText(), a.getMaLoaiSanPham());
        fillToBoard(snList);
    }//GEN-LAST:event_cbxLoaiSanPham2ItemStateChanged

    private void tblDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatHangMouseClicked
        int selectRow = tblDatHang.getSelectedRow();

        decreaseCostInTable(selectRow);
        decreaseAmount(selectRow);
        lblTongTien.setText(getTongTien());
    }//GEN-LAST:event_tblDatHangMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        tableThanhToan.setRowCount(0);
        lblTongTien.setText("0.000đ");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        LoaiSanPham a = ((LoaiSanPham) comboboxLoai.getSelectedItem());
        List<SanPham> snList = sanPhamDAO.selectByTen(txtTimKiem.getText(), a.getMaLoaiSanPham());
        fillToBoard(snList);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SanPhamBoard;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLoaiSanPham;
    private javax.swing.JButton btnLuong;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cbxLoaiSanPham2;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlScreenMain;
    private javax.swing.JPanel pnlThanhToan;
    private javax.swing.JTable tblDatHang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel tableThanhToan;
    private DefaultComboBoxModel comboboxLoai;

    private LoaiSanPhamDAO loaiSanPhamDAO;
    private SanPhamDAO sanPhamDAO;

    private void initialization() {
        tableThanhToan = (DefaultTableModel) tblDatHang.getModel();
        comboboxLoai = (DefaultComboBoxModel) cbxLoaiSanPham2.getModel();

        loaiSanPhamDAO = new LoaiSanPhamDAO();
        sanPhamDAO = new SanPhamDAO();

        fillLoai();
    }

    public void showForm(JComponent form) {
        this.alignSubForm(form);
        desktop.add(form);
        form.setVisible(true);
    }

    // căn form con ra giữa
    private void alignSubForm(JComponent form) {
        form.setLocation(this.getWidthCenter(form), this.getHeightCenter(form));
    }

    // lấy chiều ngang để căn form con ra giữa
    private int getWidthCenter(JComponent form) {
        int widthSuper = this.getWidth();
        int widthSub = form.getWidth();
        return (widthSuper - widthSub) / 2;
    }

    // lất dài để căn form con ra giữa
    private int getHeightCenter(JComponent form) {
        int heightSuper = this.getHeight();
        int heightSub = form.getHeight();
        return (heightSuper - heightSub) / 2;
    }

    private boolean isAccess() {
        if (!Auth.isManger()) {
            MsgBox.notify("Ban khong co quyen!", this);
            return false;
        }
        return true;
    }

    private void fillLoai() {
        comboboxLoai.removeAllElements();
        loaiSanPhamDAO.selectAll().forEach((x) -> {
            comboboxLoai.addElement(x);
        });
    }

    private void fillToBoard(List<SanPham> sanPhamList) {
        deleteBoard(SanPhamBoard);

        double row = (double) sanPhamList.size() / 3;
        int heightBoard = (int) (Math.ceil(row) * 200 + 100); // chieu dai cua bang chua san pham
        SanPhamBoard.setPreferredSize(new Dimension(677, heightBoard)); // SET kich thuoc cho bang san pham

        sanPhamList.forEach((x) -> {
            createBoard(x);
        });
    }

    private void createBoard(SanPham sp) {
        JPanel board = new JPanel(null);
        Dimension size = new Dimension(206, 200);
        board.setPreferredSize(size);
        board.setSize(size);

        board.add(createName(sp.getTenSanPham()));
        board.add(createCost(sp.getDonGia()));
        board.add(createImage(sp.getHinhAnh()));

        board.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                fillDatHang(sp);
            }
        });

        board.setCursor(new Cursor(Cursor.HAND_CURSOR));

        SanPhamBoard.add(board);
    }

    private JLabel createName(String name) {
        JLabel lblName = new JLabel(name);
        lblName.setFont(new Font("monospaced", Font.BOLD, 14));
        lblName.setBounds(1, 169, 206, 30);
        lblName.setHorizontalAlignment(JLabel.CENTER);
        lblName.setBackground(Color.white);
        lblName.setOpaque(true);

        return lblName;
    }

    private JLabel createImage(String pathImage) {
        JLabel lblImage = new JLabel();
        lblImage.setBounds(0, 0, 206, 170);
        lblImage.setIcon(ImageHelper.getImage(pathImage, lblImage.getWidth(), lblImage.getHeight()));
        return lblImage;
    }

    private JLabel createCost(int cost) {
        JLabel lblcost = new JLabel(cost + "K");
        lblcost.setForeground(Color.WHITE);
        lblcost.setFont(new Font("tahoma", Font.BOLD, 14));
        lblcost.setHorizontalAlignment(JLabel.CENTER);
        lblcost.setBounds(160, 0, 50, 50);
        lblcost.setBackground(Color.GREEN);
        lblcost.setOpaque(true);

        return lblcost;
    }

    private int index; // kiem tra san pham dang ton tai o dong nao
    private void fillDatHang(SanPham sp) {
        if (isExisInTable(sp.getMaSanPham())) {
            increaseAmountInTable(index);
            increaseCostInTable(index);
            lblTongTien.setText(getTongTien());
            return;
        }

        try {
            tableThanhToan.addRow(new Object[]{
                sp.getMaSanPham(),
                sp.getTenSanPham(),
                1, // amount
                LocalVietNam.getCurrency(sp.getDonGia())
            });
            lblTongTien.setText(getTongTien());
        } catch (FormatVietNamException vn) {
            MsgBox.notify(vn.getMessage(), this);
        }
    }

    private boolean isExisInTable(String maSanPham) {
        int row = tableThanhToan.getRowCount();

        for (int i = 0; i < row; i++) {
            String nameInTable = tableThanhToan.getValueAt(i, 0).toString();
            if (maSanPham.equalsIgnoreCase(nameInTable)) {
                index = i;
                return true;
            }
        }
        return false;
    }

    private void increaseAmountInTable(int row) {
        int amount = (int) tblDatHang.getValueAt(row, 2);
        tblDatHang.setValueAt(++amount, row, 2);
    }

    private void increaseCostInTable(int row) {
        String maSp = (String) tableThanhToan.getValueAt(row, 0);
        SanPham sp = sanPhamDAO.selectByID(maSp);
        
        int amount = (int) tableThanhToan.getValueAt(row, 2);
        try {
            tblDatHang.setValueAt(LocalVietNam.getCurrency(sp.getDonGia() * amount), row, 3);
        } catch (FormatVietNamException e) {
            e.printStackTrace();
            tblDatHang.setValueAt("error", row, 3);
        }
    }

    private void decreaseAmount(int row) {
        int amount = (int) tableThanhToan.getValueAt(row, 2);
        if (amount == 1) {
            tableThanhToan.removeRow(row);
            return;
        }

        tableThanhToan.setValueAt(--amount, row, 2);
    }

    private void decreaseCostInTable(int row) {
        String maSp = (String) tableThanhToan.getValueAt(row, 0);
        SanPham sp = sanPhamDAO.selectByID(maSp);

        String costs = (String) tblDatHang.getValueAt(row, 3);
        int price = Integer.parseInt(costs.substring(0, costs.indexOf(".")));
        try {
            tblDatHang.setValueAt(LocalVietNam.getCurrency(price - sp.getDonGia()), row, 3);
        } catch (FormatVietNamException vn) {
            vn.printStackTrace();
            tblDatHang.setValueAt("error", row, 3);
        }
    }

    private String getTongTien() {
        int tongTien = 0;
        for (int i = 0; i < tblDatHang.getRowCount(); i++) {
            String cost = (String) tblDatHang.getValueAt(i, 3);
            int price = Integer.parseInt(cost.substring(0, cost.indexOf(".")));
            tongTien += price;
        }
        try {
            return LocalVietNam.getCurrency(tongTien);
        } catch (FormatVietNamException e) {
            return "error";
        }

    }

    private void deleteBoard(JPanel sanPhamBoard) {
        sanPhamBoard.removeAll();
        sanPhamBoard.revalidate();
        sanPhamBoard.repaint();
    }
}
